title: 'Salvador BitDevs'
tagline: 'BitDevs é uma comunidade para aqueles interessados em discutir e participar na pesquisa e desenvolvimento do Bitcoin e protocolos relacionados.'

menu:
  - {name: 'Sobre', url: '/about'}
  - {name: 'Eventos', url: '/events'}
  - {name: 'Meetup', url: 'https://www.meetup.com/BitDevsSSA/', external: true}
